/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bigproject2;

import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Abdelrheem
 */
public class ResturantWindow extends javax.swing.JFrame {

    int s_chickenNum, s_meatNum, c_chickenNum, c_meatNum, waterNum, juiceNum, pepsiNum;
    double s_chickenPrice, s_meatPrice, c_chickenPrice, c_meatPrice, waterPrice, juicePrice, pepsiPrice;
    final double S_CHICKEN_COST = 30.0, C_CHICKEN_COST = 40.0, S_MEAT_COST = 25.0, C_MEAT_COST = 35.0, PEPSI_COST = 10.0, WATER_COST = 3.0, JUICE_COST = 15.0;
    double subtotal, vat, total;
    int customerCounter;
    PrintWriter output;

    public ResturantWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chickenCounter = new javax.swing.JSpinner();
        meatCounter = new javax.swing.JSpinner();
        chickenPriceLabel = new javax.swing.JLabel();
        chickenCheese = new javax.swing.JCheckBox();
        meatCheese = new javax.swing.JCheckBox();
        meatPriceLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        meatPriceLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        chickenCounter1 = new javax.swing.JSpinner();
        meatCounter1 = new javax.swing.JSpinner();
        chickenPriceLabel1 = new javax.swing.JLabel();
        chickenCheese1 = new javax.swing.JCheckBox();
        meatCheese1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        waterCounter = new javax.swing.JSpinner();
        juiceCounter = new javax.swing.JSpinner();
        waterPriceLabel = new javax.swing.JLabel();
        juicePriceLabel = new javax.swing.JLabel();
        waterCounter1 = new javax.swing.JSpinner();
        waterPriceLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        customerCounterLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        calculate3 = new javax.swing.JButton();
        saveBill3 = new javax.swing.JButton();
        newBill3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        subtotalLabel = new javax.swing.JLabel();
        vatLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ساندويتش", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("شاورما دجاج");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("شاورما لحم");

        chickenCounter.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        chickenCounter.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                chickenCounterAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        chickenCounter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chickenCounterStateChanged(evt);
            }
        });

        meatCounter.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        meatCounter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                meatCounterStateChanged(evt);
            }
        });

        chickenPriceLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chickenPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chickenPriceLabel.setText("0.0 جنيه");

        chickenCheese.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chickenCheese.setText("جبنة");
        chickenCheese.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        chickenCheese.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chickenCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenCheeseActionPerformed(evt);
            }
        });

        meatCheese.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        meatCheese.setText("جبنة");
        meatCheese.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        meatCheese.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        meatCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meatCheeseActionPerformed(evt);
            }
        });

        meatPriceLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        meatPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        meatPriceLabel.setText("0.0 جنيه");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chickenPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(meatPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(meatCheese)
                    .addComponent(chickenCheese))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(meatCounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chickenCounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(chickenCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chickenCheese)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chickenPriceLabel)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(meatPriceLabel)
                    .addComponent(meatCheese)
                    .addComponent(meatCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "كريب", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        meatPriceLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        meatPriceLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        meatPriceLabel1.setText("0.0 جنيه");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("شاورما دجاج");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("شاورما لحم");

        chickenCounter1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        chickenCounter1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chickenCounter1StateChanged(evt);
            }
        });

        meatCounter1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        meatCounter1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                meatCounter1StateChanged(evt);
            }
        });

        chickenPriceLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chickenPriceLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chickenPriceLabel1.setText("0.0 جنيه");

        chickenCheese1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chickenCheese1.setText("جبنة");
        chickenCheese1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        chickenCheese1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chickenCheese1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenCheese1ActionPerformed(evt);
            }
        });

        meatCheese1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        meatCheese1.setText("جبنة");
        meatCheese1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        meatCheese1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        meatCheese1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meatCheese1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chickenPriceLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meatPriceLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(meatCheese1)
                    .addComponent(chickenCheese1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(meatCounter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chickenCounter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel5)
                            .addComponent(chickenCounter1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chickenCheese1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chickenPriceLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(meatPriceLabel1)
                    .addComponent(meatCheese1)
                    .addComponent(meatCounter1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "المشروبات", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ماء");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("عصير");

        waterCounter.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        waterCounter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                waterCounterStateChanged(evt);
            }
        });

        juiceCounter.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        juiceCounter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                juiceCounterStateChanged(evt);
            }
        });

        waterPriceLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        waterPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        waterPriceLabel.setText("0.0 جنيه");

        juicePriceLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        juicePriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        juicePriceLabel.setText("0.0 جنيه ");

        waterCounter1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        waterCounter1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                waterCounter1StateChanged(evt);
            }
        });

        waterPriceLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        waterPriceLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        waterPriceLabel1.setText("0.0 جنيه");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("بيبسى");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(juicePriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(juiceCounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(waterPriceLabel)
                        .addGap(17, 17, 17)
                        .addComponent(waterCounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(waterPriceLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(waterCounter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(juicePriceLabel)
                    .addComponent(juiceCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(waterPriceLabel)
                    .addComponent(jLabel6)
                    .addComponent(waterCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(waterPriceLabel1)
                    .addComponent(jLabel8)
                    .addComponent(waterCounter1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        customerCounterLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        customerCounterLabel.setText("رقم الفاتورة: 0");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "خيارات", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        calculate3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calculate3.setText("حساب");
        calculate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate3ActionPerformed(evt);
            }
        });

        saveBill3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveBill3.setText("احفظ الفاتورة");
        saveBill3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBill3ActionPerformed(evt);
            }
        });

        newBill3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newBill3.setText("فاتورة جديدة");
        newBill3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBill3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(newBill3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(saveBill3))
                    .addComponent(calculate3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calculate3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBill3)
                    .addComponent(newBill3))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bigproject2/shawarma.png"))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "الحساب", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        subtotalLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subtotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        subtotalLabel.setText("المجموع: 0.0 جنيه");

        vatLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vatLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vatLabel.setText("الضريبة: 0.0 جنيه");

        totalLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalLabel.setText("الإجمالي: 0.0 جنيه");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(vatLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subtotalLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subtotalLabel)
                .addGap(12, 12, 12)
                .addComponent(vatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Resturant System");

        exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 0));
        exit.setText("خروج");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(customerCounterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(customerCounterLabel))
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chickenCounterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chickenCounterStateChanged

        s_chickenNum = (Integer) chickenCounter.getValue();
        s_chickenPrice = s_chickenNum * S_CHICKEN_COST;
        chickenPriceLabel.setText(s_chickenPrice + " جنيه");
    }//GEN-LAST:event_chickenCounterStateChanged

    private void meatCounterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_meatCounterStateChanged

        s_meatNum = (Integer) meatCounter.getValue();
        s_meatPrice = s_meatNum * S_MEAT_COST;
        meatPriceLabel.setText(s_meatPrice + " جنيه");
    }//GEN-LAST:event_meatCounterStateChanged

    private void chickenCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenCheeseActionPerformed

        if (chickenCheese.isEnabled()) {
            s_chickenPrice += s_chickenNum;
            chickenPriceLabel.setText(s_chickenPrice + " جنيه");
        }
    }//GEN-LAST:event_chickenCheeseActionPerformed

    private void meatCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meatCheeseActionPerformed

        if (meatCheese.isEnabled()) {
            s_meatPrice += s_meatNum;
            meatPriceLabel.setText(s_meatPrice + " جنيه");
        }
    }//GEN-LAST:event_meatCheeseActionPerformed

    private void chickenCounter1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chickenCounter1StateChanged
        c_chickenNum = (Integer) chickenCounter1.getValue();
        c_chickenPrice = c_chickenNum * C_CHICKEN_COST;
        chickenPriceLabel1.setText(c_chickenPrice + " جنيه");
    }//GEN-LAST:event_chickenCounter1StateChanged

    private void meatCounter1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_meatCounter1StateChanged
        c_meatNum = (Integer) meatCounter1.getValue();
        c_meatPrice = c_meatNum * C_MEAT_COST;
        meatPriceLabel1.setText(c_meatPrice + " جنيه");
    }//GEN-LAST:event_meatCounter1StateChanged

    private void chickenCheese1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenCheese1ActionPerformed
        if (chickenCheese1.isEnabled()) {
            c_chickenPrice += c_chickenNum;
            chickenPriceLabel1.setText(c_chickenPrice + " جنيه");
        }
    }//GEN-LAST:event_chickenCheese1ActionPerformed

    private void meatCheese1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meatCheese1ActionPerformed
        if (meatCheese1.isEnabled()) {
            c_meatPrice += c_meatNum;
            meatPriceLabel1.setText(c_meatPrice + " جنيه");
        }
    }//GEN-LAST:event_meatCheese1ActionPerformed

    private void waterCounterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_waterCounterStateChanged

        waterNum = (Integer) waterCounter.getValue();
        waterPrice = waterNum * WATER_COST;
        waterPriceLabel.setText(waterPrice + " جنيه");
    }//GEN-LAST:event_waterCounterStateChanged

    private void juiceCounterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_juiceCounterStateChanged

        juiceNum = (Integer) juiceCounter.getValue();
        juicePrice = juiceNum * JUICE_COST;
        juicePriceLabel.setText(juicePrice + " جنيه");
    }//GEN-LAST:event_juiceCounterStateChanged

    private void waterCounter1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_waterCounter1StateChanged
        pepsiNum = (Integer) waterCounter1.getValue();
        pepsiPrice = pepsiNum * PEPSI_COST;
        waterPriceLabel1.setText(pepsiPrice + " جنيه");    }//GEN-LAST:event_waterCounter1StateChanged

    private void calculate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate3ActionPerformed

        // Calculate subtotal
        subtotal = s_chickenPrice + s_meatPrice + c_chickenPrice + c_meatPrice + waterPrice + juicePrice;
        subtotalLabel.setText("المجموع: " + subtotal + " جنيه");

        // Calculate vat
        vat = subtotal * 0.05;
        vat = vat * 100;
        vat = (double) ((int) vat);
        vat = vat / 100;
        vatLabel.setText("الضريبة: " + vat + " جنيه");

        // Calculate total
        total = subtotal + vat;
        totalLabel.setText("الإجمالي: " + total + " جنيه");
    }//GEN-LAST:event_calculate3ActionPerformed

    private void saveBill3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBill3ActionPerformed

        try {

            if (total != 0) {

                output = new PrintWriter("billNo." + customerCounter + ".txt");

                output.println(customerCounter + " فاتورة رقم");
                output.println("==============");

                if (s_chickenNum != 0) {
                    output.print(s_chickenNum + " ساندويتش شاورما دجاج");

                    if (chickenCheese.isEnabled()) {
                        output.println(" مع الجبنة");
                    }
                    output.println(s_chickenPrice + " جنيه");
                }
                if (c_chickenNum != 0) {
                    output.print(c_chickenNum + " كريب شاورما دجاجك");

                    if (chickenCheese1.isEnabled()) {
                        output.println(" مع الجبنة");
                    }
                    output.println(c_chickenPrice + " جنيه");
                }

                if (s_meatNum != 0) {
                    output.print(s_meatNum + " ساندويتش شاورما لحم");

                    if (meatCheese.isEnabled()) {
                        output.println(" مع الجبنة");
                    }
                    output.println(s_meatPrice + " جنيه");
                }
                if (c_meatNum != 0) {
                    output.print(c_meatNum + " كريب شاورما لحم");

                    if (meatCheese1.isEnabled()) {
                        output.println(" مع الجبنة");
                    }
                    output.println(c_meatPrice + " جنيه");
                }

                if (waterNum != 0) {
                    output.println(waterNum + " ماء");
                    output.println(waterPrice + " جنيه");
                }

                if (juiceNum != 0) {
                    output.println(juiceNum + " عصير");
                    output.println(juicePrice + " جنيه");
                }
                if (pepsiNum != 0) {
                    output.println(pepsiNum + " عصير");
                    output.println(pepsiPrice + " جنيه");
                }

                output.println("----");
                output.println("المجموع: " + subtotal + " جنيه");
                output.println("الضريبة: " + vat + " جنيه");
                output.println("الإجمالي: " + total + " جنيه");
                output.println();
                output.println("*** شكرا لطلبك ***");

                output.close();

            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(ResturantWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_saveBill3ActionPerformed

    private void newBill3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBill3ActionPerformed

        if (total != 0) {
            customerCounter++;
            customerCounterLabel.setText("رقم الفاتورة: " + customerCounter);

            chickenCounter.setValue(0);
            meatCounter.setValue(0);
            chickenCounter1.setValue(0);
            meatCounter1.setValue(0);
            waterCounter.setValue(0);
            waterCounter1.setValue(0);
            juiceCounter.setValue(0);

            chickenCheese.setSelected(false);
            meatCheese.setSelected(false);
            chickenCheese1.setSelected(false);
            meatCheese1.setSelected(false);

            subtotalLabel.setText("المجموع: 0.0 جنيه");
            vatLabel.setText("الضريبة: 0.0 جنيه");
            totalLabel.setText("الإجمالي: 0.0 جنيه");

            subtotal = 0;
            vat = 0;
            total = 0;
        }
    }//GEN-LAST:event_newBill3ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void chickenCounterAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_chickenCounterAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_chickenCounterAncestorAdded

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Image img = ImageIO.read(getClass().getResource("download.png"));
            this.setIconImage(img);
            this.setLocationRelativeTo(null);
        } catch (IOException ex) {
            Logger.getLogger(ResturantWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResturantWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResturantWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResturantWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResturantWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResturantWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate3;
    private javax.swing.JCheckBox chickenCheese;
    private javax.swing.JCheckBox chickenCheese1;
    private javax.swing.JSpinner chickenCounter;
    private javax.swing.JSpinner chickenCounter1;
    private javax.swing.JLabel chickenPriceLabel;
    private javax.swing.JLabel chickenPriceLabel1;
    private javax.swing.JLabel customerCounterLabel;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner juiceCounter;
    private javax.swing.JLabel juicePriceLabel;
    private javax.swing.JCheckBox meatCheese;
    private javax.swing.JCheckBox meatCheese1;
    private javax.swing.JSpinner meatCounter;
    private javax.swing.JSpinner meatCounter1;
    private javax.swing.JLabel meatPriceLabel;
    private javax.swing.JLabel meatPriceLabel1;
    private javax.swing.JButton newBill3;
    private javax.swing.JButton saveBill3;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel vatLabel;
    private javax.swing.JSpinner waterCounter;
    private javax.swing.JSpinner waterCounter1;
    private javax.swing.JLabel waterPriceLabel;
    private javax.swing.JLabel waterPriceLabel1;
    // End of variables declaration//GEN-END:variables
}
